### ISSUE TITLE
Not working on (web) export in Godot 3.5.1

### ISSUE THREAD

**Issue by Oahid243** [TheDuckCow/godot-road-generator#111]
The generated road works fine on pc with GLES2 but when exported for web the road is gone. Is there any fix?

**Comment by TheDuckCow** [comment]
Thanks for flagging the issue, we haven't tried in a web export at this moment. Are there any logs you can share output to the web console? You can also try explicitly forcing a rebuild of the roads using the roadnetwork object:

```
var network = $RoadNetwork # node in scene
network.rebuild_segments(true) # true is for the "clear_existing" arg.
```

if this doesn't work for you, our team can look a bit further into it in a simple web export ourselves.

**Comment by TheDuckCow** [comment]
Hey @Oahid243 I did some further checking, and it may have been an issue with releases _in general_. Can you verify if the code currently on main works now? (noting [this commit](https://github.com/TheDuckCow/godot-road-generator/commit/743e5a56ffe987c01ccd8ada62348f30a276784b) that I pushed, which makes roads appear in exports again for me now)

**Comment by TheDuckCow** [comment]
Confirmed that this issue has been fixed in the main and dev branch, will be pushing a new release later this week (but you could already use these branches).

Simple example having exported via web here:

![Screen Shot 2023-07-17 at 10 27 33 PM](https://github.com/TheDuckCow/godot-road-generator/assets/2958461/4ac42644-8993-402b-851b-4118de3174d9)

Closing given it will be part of this release.
