### ISSUE TITLE
Road tilt contains little 'kinks'

### ISSUE THREAD

**Issue by TheDuckCow** [TheDuckCow/godot-road-generator#14]
The tilting of roads via road segments is working much better, but I notice now that there is some 'kinking' right around the roadpoint itself. Almost seems like we're not effectively setting the falloff of the underyinging curves. 

<img width="577" alt="Screen Shot 2022-10-27 at 9 17 57 PM" src="https://user-images.githubusercontent.com/2958461/198501528-abe49a00-b225-40e1-a66a-b8e2f5e4efe0.png">

In the wheel steal project, this is how the updated road generator looks. In this video in particular, it seems interesting how it's almost like the tilt of one curve before isn't mapping to the ends of the other one. It's possible that this is a limitation of using the curve tilts of the non-connected curve segments under the hood for tilting.

https://user-images.githubusercontent.com/2958461/198502027-2884a6f0-ba7c-42c1-bc1f-b6c7e73a0518.mp4

**Comment by bdog2112** [comment]
It appears that the end points of the curves are not rotated to match their associated RoadPoints. This condition is currently hidden from view because the drawing code uses the ROADPOINT rotation for drawing Segment start and end loops and various CURVE values for drawing the rest of the Segment loops.

If we change the code to use the CURVE values for drawing the start and end loops, then we can clearly see the rotation isn't quite right on those loops.

Curve points don't have an explicit rotation property. Hence, I'm investigating whether we can even set the curve start/end rotation more accurately. If that's not possible, then I'll look at interpolating between the RoadPoints and the curve points.
